services:
  - type: web
    name: caretrace-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    autoDeploy: false
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: caretrace_ai
      - key: MONGO_DB
        value: caretrace_ai
      - key: POSTGRES_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: CORS_ORIGINS
        sync: false
